"""Built-in transposing-instrument profile catalog."""

from __future__ import annotations

from timbrescribe.domain.score import InstrumentProfile, PitchRange

_PROFILES = (
    InstrumentProfile(
        "piano",
        "Piano",
        "keyboard",
        0,
        False,
        "grand",
        2,
        PitchRange(21, 108),
        PitchRange(21, 108),
        0,
        0,
        0,
        "grand-staff",
    ),
    InstrumentProfile(
        "flute",
        "Flute",
        "woodwind",
        73,
        False,
        "treble",
        1,
        PitchRange(60, 96),
        PitchRange(60, 96),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "clarinet-bb",
        "B-flat Clarinet",
        "woodwind",
        71,
        False,
        "treble",
        1,
        PitchRange(50, 94),
        PitchRange(48, 92),
        -1,
        -2,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "trumpet-bb",
        "B-flat Trumpet",
        "brass",
        56,
        False,
        "treble",
        1,
        PitchRange(54, 82),
        PitchRange(52, 80),
        -1,
        -2,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "alto-sax-eb",
        "E-flat Alto Saxophone",
        "woodwind",
        65,
        False,
        "treble",
        1,
        PitchRange(49, 87),
        PitchRange(40, 78),
        -5,
        -9,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "tenor-sax-bb",
        "B-flat Tenor Saxophone",
        "woodwind",
        66,
        False,
        "treble",
        1,
        PitchRange(49, 87),
        PitchRange(35, 73),
        -1,
        -2,
        -1,
        "single-staff",
    ),
    InstrumentProfile(
        "horn-f",
        "Horn in F",
        "brass",
        60,
        False,
        "treble",
        1,
        PitchRange(42, 84),
        PitchRange(35, 77),
        -4,
        -7,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "generic-instrument",
        "Generic Instrument",
        "other",
        0,
        False,
        "treble",
        1,
        PitchRange(0, 127),
        PitchRange(0, 127),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "electric-piano",
        "Electric Piano",
        "keyboard",
        4,
        False,
        "grand",
        2,
        PitchRange(21, 108),
        PitchRange(21, 108),
        0,
        0,
        0,
        "grand-staff",
    ),
    InstrumentProfile(
        "chromatic-percussion",
        "Chromatic Percussion",
        "percussion",
        11,
        False,
        "treble",
        1,
        PitchRange(36, 96),
        PitchRange(36, 96),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "organ",
        "Organ",
        "keyboard",
        19,
        False,
        "grand",
        2,
        PitchRange(24, 108),
        PitchRange(24, 108),
        0,
        0,
        0,
        "grand-staff",
    ),
    InstrumentProfile(
        "guitar",
        "Guitar",
        "strings",
        24,
        False,
        "treble",
        1,
        PitchRange(40, 88),
        PitchRange(40, 88),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "bass-guitar",
        "Bass Guitar",
        "strings",
        32,
        False,
        "bass",
        1,
        PitchRange(28, 67),
        PitchRange(28, 67),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "violin",
        "Violin",
        "strings",
        40,
        False,
        "treble",
        1,
        PitchRange(55, 103),
        PitchRange(55, 103),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "viola",
        "Viola",
        "strings",
        41,
        False,
        "alto",
        1,
        PitchRange(48, 91),
        PitchRange(48, 91),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "cello",
        "Cello",
        "strings",
        42,
        False,
        "bass",
        1,
        PitchRange(36, 84),
        PitchRange(36, 84),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "contrabass",
        "Contrabass",
        "strings",
        43,
        False,
        "bass",
        1,
        PitchRange(28, 67),
        PitchRange(28, 67),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "harp",
        "Orchestral Harp",
        "strings",
        46,
        False,
        "grand",
        2,
        PitchRange(24, 103),
        PitchRange(24, 103),
        0,
        0,
        0,
        "grand-staff",
    ),
    InstrumentProfile(
        "timpani",
        "Timpani",
        "percussion",
        47,
        False,
        "bass",
        1,
        PitchRange(36, 57),
        PitchRange(36, 57),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "string-ensemble",
        "String Ensemble",
        "strings",
        48,
        False,
        "treble",
        1,
        PitchRange(28, 103),
        PitchRange(28, 103),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "voice",
        "Voice",
        "voice",
        52,
        False,
        "treble",
        1,
        PitchRange(36, 96),
        PitchRange(36, 96),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "trombone",
        "Trombone",
        "brass",
        57,
        False,
        "bass",
        1,
        PitchRange(34, 72),
        PitchRange(34, 72),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "tuba",
        "Tuba",
        "brass",
        58,
        False,
        "bass",
        1,
        PitchRange(24, 60),
        PitchRange(24, 60),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "oboe",
        "Oboe",
        "woodwind",
        68,
        False,
        "treble",
        1,
        PitchRange(58, 91),
        PitchRange(58, 91),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "english-horn",
        "English Horn",
        "woodwind",
        69,
        False,
        "treble",
        1,
        PitchRange(52, 81),
        PitchRange(45, 74),
        -4,
        -7,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "bassoon",
        "Bassoon",
        "woodwind",
        70,
        False,
        "bass",
        1,
        PitchRange(34, 75),
        PitchRange(34, 75),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "synth",
        "Synthesizer",
        "synth",
        80,
        False,
        "treble",
        1,
        PitchRange(0, 127),
        PitchRange(0, 127),
        0,
        0,
        0,
        "single-staff",
    ),
    InstrumentProfile(
        "drums",
        "Drums",
        "percussion",
        0,
        True,
        "percussion",
        1,
        PitchRange(0, 127),
        PitchRange(0, 127),
        0,
        0,
        0,
        "percussion-staff",
    ),
)

INSTRUMENT_PROFILES = {profile.id: profile for profile in _PROFILES}


def get_instrument_profile(profile_id: str) -> InstrumentProfile:
    try:
        return INSTRUMENT_PROFILES[profile_id]
    except KeyError as exc:
        raise ValueError(f"Unknown instrument profile: {profile_id}") from exc
